version: '3.8'

services:

  graffiti-link-service:
    container_name: graffiti-link-service
    build: app
    volumes:
      - ./app:/mount/app
    depends_on:
      - mongo

  mongo:
    container_name: graffiti-mongo
    image: mongo:7.0.3-jammy
    restart: always
    command: "--bind_ip_all --replSet rs0 --quiet --logpath /dev/null"
    volumes:
      - ./config/mongo:/docker-entrypoint-initdb.d/
      - ./db:/data/db
    extra_hosts:
      - "mongo:127.0.0.1"