version: '3.8'

services:

  graffiti-link-service:
    environment:
      DEBUG: 'false'

  nginx:
    image: nginx:1.25.3-alpine-slim
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
      ONION_DOMAIN: ${ONION_DOMAIN}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
